# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-consumer-wa:
    image: mongo
    container_name: mongo-bch-consumer-wa
    ports:
      - '5556:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-bch-consumer-wa:
    image: ipfs/go-ipfs:v0.12.0
    container_name: ipfs-bch-consumer-wa
    environment:
      MY_ENV_VAR: 'placeholder'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4002:4002
      - 172.17.0.1:5002:5002
    volumes:
      - ../data/go-ipfs/data:/data/ipfs
      - ../../swarm.key:/data/ipfs/swarm.key
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#command
    # https://github.com/ipfs/go-ipfs/blob/91c52657166bcf86f2476926e4fe56694dc26562/Dockerfile#L115
    command:
      [
        'daemon',
        '--migrate=true',
        '--agent-version-suffix=docker',
        '--enable-pubsub-experiment'
      ]
    restart: always

  bch-consumer-wa:
    #build: .
    image: christroutner/ipfs-bch-wallet-consumer:v1.8.2
    container_name: bch-consumer-wa
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1500mb
    links:
      - mongo-bch-consumer-wa
      - ipfs-bch-consumer-wa
    ports:
      - '5011:5011' # <host port>:<container port>
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-bch-wallet-consumer/.ipfsdata
      - ./start-production.sh:/home/safeuser/ipfs-bch-wallet-consumer/start-production.sh
    restart: always
