# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-consumer:
    image: mongo
    container_name: mongo-bch-consumer
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-bch-consumer:
    image: ipfs/go-ipfs:v0.12.0
    container_name: ipfs-bch-consumer
    environment:
      MY_ENV_VAR: 'placeholder'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    volumes:
      - ../data/go-ipfs/data:/data/ipfs
      - ../data/go-ipfs/export:/export
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#command
    # https://github.com/ipfs/go-ipfs/blob/91c52657166bcf86f2476926e4fe56694dc26562/Dockerfile#L115
    command:
      [
        'daemon',
        '--migrate=true',
        '--agent-version-suffix=docker',
        '--enable-pubsub-experiment'
      ]
    restart: always

  bch-consumer:
    build: .
    container_name: bch-consumer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - mongo-bch-consumer
      - ipfs-bch-consumer
    ports:
      - '5010:5010' # <host port>:<container port>
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-service-provider/.ipfsdata
    restart: always
